spring:
  profiles:
    active: mysql

spring.batch.job.names: ${job.name:NONE}
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: batch_sample
      password: 1234
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3307/batch_sample?serverTimezone=UTC&characterEncoding=UTF-8
      username: batch_sample
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver